### ISSUE TITLE
Error in preview and show shadow

### ISSUE THREAD

**Issue by farsroidx** [L-Briand/ShadowLayout#4]
### I just copied your code and did not change it. But Android Studio does not show me preview and shadow. Android Studio preview shows the following error:

> **Render problem in android studio:**

```
android.renderscript.RSDriverException: Failed to create RS context.   
   at android.renderscript.RenderScript.internalCreate(RenderScript.java:1441)   
   at android.renderscript.RenderScript.create(RenderScript.java:1543)   
   at android.renderscript.RenderScript.create(RenderScript.java:1500)   
   at android.renderscript.RenderScript.create(RenderScript.java:1474)   
   at android.renderscript.RenderScript.create(RenderScript.java:1461)   
   at com.package.ShadowLayout.getScript(ShadowLayout.kt:166)   
   at com.package.ShadowLayout.updateBitmap(ShadowLayout.kt:213)   
   at com.package.ShadowLayout.setViewBounds(ShadowLayout.kt:153)   
   at com.package.ShadowLayout.onSizeChanged(ShadowLayout.kt:278)   
   at android.view.View.sizeChange(View.java:22120)   
   at android.view.View.setFrame(View.java:22072)   
   at android.view.View.layout_Original(View.java:21931)   
   at android.view.View_Delegate.layout(View_Delegate.java:91)  
   at android.view.View.layout(View.java:21920)   
   at android.view.ViewGroup.layout(ViewGroup.java:6260)   
   at androidx.constraintlayout.widget.ConstraintLayout.onLayout_Original(ConstraintLayout.java:1762)  
   at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:-1)   
   at android.view.View.layout_Original(View.java:21934)   
   at android.view.View_Delegate.layout(View_Delegate.java:91)   
   at android.view.View.layout(View.java:21920)   
   at android.view.ViewGroup.layout(ViewGroup.java:6260)   
   at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)   
   at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)   
   at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout_Original(CoordinatorLayout.java:919)   
   at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:-1)  
   at android.view.View.layout_Original(View.java:21934)   
   at android.view.View_Delegate.layout(View_Delegate.java:91)   
   at android.view.View.layout(View.java:21920)  
   at android.view.ViewGroup.layout(ViewGroup.java:6260)   
   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)    
   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)   
   at android.view.View.layout_Original(View.java:21934)  
   at android.view.View_Delegate.layout(View_Delegate.java:91)   
   at android.view.View.layout(View.java:21920)   
   at android.view.ViewGroup.layout(ViewGroup.java:6260)  
   at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)    
   at android.view.View.layout_Original(View.java:21934)    
   at android.view.View_Delegate.layout(View_Delegate.java:91)  
   at android.view.View.layout(View.java:21920)   
   at android.view.ViewGroup.layout(ViewGroup.java:6260)   
   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)    
   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)   
   at android.view.View.layout_Original(View.java:21934)   
   at android.view.View_Delegate.layout(View_Delegate.java:91)   
   at android.view.View.layout(View.java:21920)   
   at android.view.ViewGroup.layout(ViewGroup.java:6260)
```

> **Kotlin:**
```kotlin
package com.package

import android.content.Context
import android.content.res.Resources
import android.graphics.*
import android.renderscript.Allocation
import android.renderscript.Element
import android.renderscript.RenderScript
import android.renderscript.ScriptIntrinsicBlur
import android.util.AttributeSet
import android.util.DisplayMetrics
import android.view.View
import android.view.ViewOutlineProvider
import android.widget.FrameLayout
import androidx.annotation.ColorInt
import androidx.annotation.ColorRes
import androidx.annotation.DimenRes
import androidx.annotation.Nullable
import androidx.core.content.res.ResourcesCompat
import androidx.core.graphics.scaleMatrix
import androidx.core.graphics.times
import androidx.core.graphics.translationMatrix
import androidx.core.graphics.withMatrix
import com.package.R
import kotlin.math.ceil

/** A CSS like shadow */
class ShadowLayout @JvmOverloads constructor(
    context: Context,
    @Nullable attrs: AttributeSet? = null,
    defStyleAttr: Int = 0,
    defStyleRes: Int = 0
) : FrameLayout(context, attrs, defStyleAttr, defStyleRes) {

    companion object {
        @JvmField
        val ratioDpToPixels =
            Resources.getSystem().displayMetrics.densityDpi.toFloat() / DisplayMetrics.DENSITY_DEFAULT

        @JvmField
        val ratioPixelsToDp: Float = (1.0 / ratioDpToPixels.toDouble()).toFloat()

        // Thanks to this hero https://stackoverflow.com/a/41322648/4681367
        const val cssRatio: Float = 5f / 3f
    }

    // BASIC FIELDS

    private val paint = Paint(Paint.ANTI_ALIAS_FLAG or Paint.DITHER_FLAG)
    private val eraser = Paint().apply { xfermode = PorterDuffXfermode(PorterDuff.Mode.DST_OUT) }

    fun getColor(): Int = paint.color

    fun setColor(@ColorInt color: Int) {
        if (paint.color == color) return
        paint.color = color
        postInvalidate()
    }

    fun setColorRes(@ColorRes color: Int) {
        setColor(ResourcesCompat.getColor(resources, color, null))
    }

    var xShift: Float = 0f
        set(value) {
            if (field == value) return
            field = value
            postInvalidate()
        }

    fun setXShift(@DimenRes shift: Int) {
        xShift = context.resources.getDimension(shift)
    }

    var yShift: Float = 0f
        set(value) {
            if (field == value) return
            field = value
            postInvalidate()
        }

    fun setYShift(@DimenRes shift: Int) {
        yShift = context.resources.getDimension(shift)
    }

    var downscale: Float = 1f
        set(value) {
            if (field == value) return
            field = value.coerceAtLeast(0.1f)
            realRadius = radius / field
            updateBitmap()
            postInvalidate()
        }

    var radius: Float = 0f
        set(value) {
            if (field == value) return
            field = value.coerceAtLeast(0f)
            realRadius = field / downscale
            postInvalidate()
        }

    private var realRadius: Float = 0f
        set(value) {
            if (field == value) return
            field = value.coerceIn(0f, 25f) // allowed blur size on ScriptIntrinsicBlur by android
        }

    var withForeground: Boolean = true
        set(value) {
            if (field == value) return
            field = value
            postInvalidate()
        }

    var withColor: Boolean = false
        set(value) {
            if (field == value) return
            field = value
            destroyBitmap()
            updateBitmap()
            postInvalidate()
        }

    var withDpi: Boolean = true
        set(value) {
            field = value
            destroyBitmap()
            updateBitmap()
            postInvalidate()
        }

    var withCss: Boolean = true
        set(value) {
            field = value
            destroyBitmap()
            updateBitmap()
            postInvalidate()
        }

    // IN VARIABLES

    private val ratioDpToPixels get() = if (withDpi) SDKShadowLayout.ratioDpToPixels else 1f
    private val ratioPixelsToDp get() = if (withDpi) SDKShadowLayout.ratioPixelsToDp else 1f
    private val cssRatio get() = if (withCss) SDKShadowLayout.cssRatio else 1f

    // size in pixel of the blur spread
    private val pixelsOverBoundaries: Int get() = if (downscale < 1f) 25 else ceil(25f * downscale).toInt()
    private val viewBounds: Rect = Rect()
    private fun setViewBounds(width: Int, height: Int) {
        viewBounds.set(0, 0, width, height)
        println(viewBounds)
        updateBitmap()
    }

    private var blurBitmap: Bitmap? = null
    private var blurCanvas: Canvas? = null

    private var renderScript: RenderScript? = null
    private var script: ScriptIntrinsicBlur? = null
    private var inAlloc: Allocation? = null
    private var outAlloc: Allocation? = null

    private var lastWithColorScript: Boolean? = null
    private fun getScript(): Pair<ScriptIntrinsicBlur, RenderScript> {
        val renderScript = this.renderScript ?: RenderScript.create(context)
        if (lastWithColorScript != withColor) { // recreate script only if colors change
            lastWithColorScript = withColor
            script = null
        }
        if (script != null) return Pair(script!!, renderScript!!)
        val element = if (withColor) Element.U8_4(renderScript) else Element.U8(renderScript)
        script = ScriptIntrinsicBlur.create(renderScript, element)
        return Pair(script!!, renderScript!!)
    }

    private val lastBounds = Rect()
    private var lastScale = 0f
    private var lastWithColorBitmap: Boolean? = null
    private var lastWithDpi: Boolean? = null
    private var lastWithCss: Boolean? = null
    private fun updateBitmap() {
        // do not recreate if same specs.
        if (viewBounds.isEmpty || isAttachedToWindow
            && lastBounds == viewBounds
            && downscale == lastScale
            && withColor == lastWithColorBitmap
            && withDpi == lastWithDpi
            && withCss == lastWithCss
        ) return
        lastBounds.set(viewBounds)
        lastScale = downscale
        lastWithColorBitmap = withColor
        lastWithColorBitmap = withColor
        lastWithDpi = withDpi
        lastWithCss = withCss

        // create a receptacle for blur script. (MDPI / downscale) + (pixels * 2) cause blur spread in all directions
        blurBitmap?.recycle()
        blurBitmap = Bitmap.createBitmap(
            (ceil(
                (viewBounds.width().toFloat() * ratioPixelsToDp) / downscale / cssRatio
            ) + pixelsOverBoundaries * 2).toInt(),
            (ceil(
                (viewBounds.height().toFloat() * ratioPixelsToDp) / downscale / cssRatio
            ) + pixelsOverBoundaries * 2).toInt(),
            if (withColor) Bitmap.Config.ARGB_8888 else Bitmap.Config.ALPHA_8
        )
        println("lol : " + blurBitmap!!.width + ", " + blurBitmap!!.height + " -- " + pixelsOverBoundaries)

        blurCanvas = Canvas(blurBitmap!!)

        val (script, renderScript) = getScript()
        inAlloc?.destroy()
        inAlloc = Allocation.createFromBitmap(renderScript, blurBitmap)
        if (outAlloc?.type != inAlloc?.type) {
            outAlloc?.destroy()
            outAlloc = Allocation.createTyped(renderScript, inAlloc!!.type)
        }
        script.setInput(inAlloc)
    }

    private fun destroyBitmap() {
        blurBitmap?.recycle()
        blurBitmap = null
        blurCanvas = null
        script?.destroy()
        script = null
        inAlloc?.destroy()
        inAlloc = null
        outAlloc?.destroy()
        outAlloc = null
        lastBounds.setEmpty()
        lastScale = 0f
        lastWithColorScript = null
        lastWithColorBitmap = null
        lastWithDpi = null
        lastWithCss = null
    }

    override fun getOutlineProvider(): ViewOutlineProvider = object : ViewOutlineProvider() {
        override fun getOutline(view: View?, outline: Outline?) = Unit
    }

    // Overriding view

    init {
        val attributes = context.obtainStyledAttributes(
            attrs, R.styleable.SDKShadowLayout, defStyleAttr, defStyleRes
        )
        setColor(attributes.getColor(R.styleable.SDKShadowLayout_shadow_color, 51 shl 24))
        withColor = attributes.getBoolean(R.styleable.SDKShadowLayout_shadow_with_color, false)
        withForeground =
            attributes.getBoolean(R.styleable.SDKShadowLayout_shadow_with_foreground, true)
        withDpi = attributes.getBoolean(R.styleable.SDKShadowLayout_shadow_with_dpi_scale, true)
        withCss = attributes.getBoolean(R.styleable.SDKShadowLayout_shadow_with_css_scale, true)
        xShift = attributes.getDimension(R.styleable.SDKShadowLayout_shadow_x_shift, 0f)
        yShift = attributes.getDimension(R.styleable.SDKShadowLayout_shadow_y_shift, 0f)
        downscale = attributes.getFloat(R.styleable.SDKShadowLayout_shadow_downscale, 1f)
        radius = attributes.getFloat(R.styleable.SDKShadowLayout_shadow_radius, 6f)

        attributes.recycle()
        setWillNotDraw(false)
    }

    override fun onAttachedToWindow() {
        super.onAttachedToWindow()
        updateBitmap()
    }

    override fun onDetachedFromWindow() {
        super.onDetachedFromWindow()
        destroyBitmap()
    }

    override fun onSizeChanged(w: Int, h: Int, oldw: Int, oldh: Int) {
        super.onSizeChanged(w, h, oldw, oldh)
        setViewBounds(w, h)
    }

    private val blurTMatrix: Matrix // cause blur spreads
        get() = translationMatrix(pixelsOverBoundaries.toFloat(), pixelsOverBoundaries.toFloat())
    private val blurSMatrix: Matrix // to draw inside the small blurBitmap
        get() = scaleMatrix(
            ratioPixelsToDp / downscale / cssRatio,
            ratioPixelsToDp / downscale / cssRatio
        )
    private val drawTMatrix: Matrix // counterbalance for blur spread in canvas
        get() = translationMatrix(
            -(pixelsOverBoundaries * ratioDpToPixels * downscale * cssRatio),
            -(pixelsOverBoundaries * ratioDpToPixels * downscale * cssRatio)
        )
    private val drawSMatrix: Matrix // enlarge blur image to canvas size
        get() = scaleMatrix(
            ratioDpToPixels * downscale * cssRatio,
            ratioDpToPixels * downscale * cssRatio
        )
    private val shiftTMatrix: Matrix // User want a nice shifted shadow
        get() = translationMatrix(
            xShift / downscale / cssRatio,
            yShift / downscale / cssRatio
        )

    override fun draw(canvas: Canvas?) {
        canvas ?: return
        if (blurCanvas != null) {
            blurCanvas!!.drawRect(blurCanvas!!.clipBounds, eraser)
            blurCanvas!!.withMatrix(blurTMatrix * blurSMatrix) { super.draw(blurCanvas) }
            if (realRadius > 0f) { // Do not blur if no radius
                val (script) = getScript()
                script.setRadius(realRadius)
                inAlloc?.copyFrom(blurBitmap)
                script.forEach(outAlloc)
                outAlloc?.copyTo(blurBitmap)
            }
            canvas.withMatrix(drawTMatrix * drawSMatrix * shiftTMatrix) {
                canvas.drawBitmap(blurBitmap!!, 0f, 0f, paint)
            }
        }
        if (withForeground) super.draw(canvas)
    }
}
```

> **XML:**
```xml
<com.package.ShadowLayout
    android:layout_width="250dp"
    android:layout_height="250dp"
    android:layout_margin="12dp"
    android:background="@drawable/irx_shape_big"
    android:padding="16dp"
    app:layout_constraintBottom_toBottomOf="parent"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toBottomOf="@+id/appBar"
    app:layout_constraintVertical_bias="0.7"
    app:shadow_color="#FF000000"
    app:shadow_downscale="1"
    app:shadow_radius="25"
    app:shadow_with_color="true"
    app:shadow_with_css_scale="true"
    app:shadow_with_dpi_scale="true"
    app:shadow_with_foreground="true"
    app:shadow_x_shift="4dp"
    app:shadow_y_shift="10dp">

    <androidx.appcompat.widget.AppCompatTextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="The quick brown fox jump over the lazy dog"
        android:textColor="#808"
        android:textSize="16sp" />

</com.package.ShadowLayout>
```

### Shadow not working...
![alt text](https://s16.picofile.com/file/8429595168/photo.png)

**Comment by L-Briand** [comment]
Hi @farsroidx,

Sorry for the late response.

RenderScripts are not available in AndroidStudio render engine and this layout is based on the Android blur RenderScript... Therefore AFAIK it's not possible render a preview directly inside AndroidStudio.

:confused:

**Comment by farsroidx** [comment]
thanks @L-Briand for your response.
But the final image inserted in the question is after running the program on the real device and does not show shadows on the real device...

**Comment by farsroidx** [comment]
thanks @L-Briand for your response.
But the final image inserted in the question is after running the program on the real device and does not show shadows on the real device...

**Comment by L-Briand** [comment]
Hi @farsroidx,
I have published a version of this lib on maven Central. Maybe try out this newer version.
Can you share your full xml to let me see any problem and try to reproduce the error ?
Also, on what device you run it ?
